version: "2"
services:
  # Startup - Init script to initialize indices and templates and startup webserver
  startup:
    build: ./docker/startup
    container_name: brewviz-start
    ports:
      - 8000:80
    volumes:
      - ./www:/var
    links:
      - elasticsearch
    depends_on: 
      - "elasticsearch"
    command: bash /opt/entrypoint.sh

  # ELK Stack
  elasticsearch:
    build: ./docker/es
    container_name: brewviz-elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
      - ./docker/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    build: ./docker/logstash
    container_name: brewviz-logstash
    command: -f /etc/logstash/conf.d
    volumes:
      - ./scripts/data:/var/log/brew
      - ./docker/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./docker/logstash/brew.json:/usr/share/logstash/templates/brew.json
    links:
      - elasticsearch
      - startup
    environment:
      LS_HEAP_SIZE: "2048m"
      
  kibana:
    build: ./docker/kibana
    container_name: brewviz-kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
