version: "2"
services:
  # ELK Stack
  elasticsearch:
    build: ./docker/es
    container_name: brewviz-elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
      - ./docker/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    build: ./docker/logstash
    container_name: brewviz-logstash
    command: -f /etc/logstash/conf.d
    volumes:
      - ./data:/var/log/brew
      - ./docker/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./docker/logstash/brew.json:/usr/share/logstash/templates/brew.json
    links:
      - elasticsearch
    environment:
      LS_HEAP_SIZE: "2048m"
  kibana:
    build: ./docker/kibana
    container_name: brewviz-kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
