version: "2"
services:
  # ELK Stack
  elasticsearch:
    build: ./docker/es
    container_name: brewviz-elastic
    ports:
      - 9200:9200
      # - 9300:9300
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
  logstash:
    restart: always
    build: ./docker/logstash
    container_name: brewviz-logstash
    volumes:
      - ./data:/var/log/brew
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    build: ./docker/kibana
    container_name: brewviz-kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch